//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Ban_Hang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONDATHANG
    {
        public int MACHITIETDONDATHANG { get; set; }
        public string MADONDATHANG { get; set; }
        public string MAHANG { get; set; }
        public int SOLUONGNHAP { get; set; }
        public Nullable<int> TONGTIENCHITIET { get; set; }
    
        public virtual DONDATHANG DONDATHANG { get; set; }
        public virtual HANG HANG { get; set; }
    }
}
