//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class HOADONBH
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HOADONBH()
    {
        this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        this.THONGKEHOADONs = new HashSet<THONGKEHOADON>();
    }

    public string MAHOADONBH { get; set; }
    public Nullable<System.DateTime> NGAYLAPHOADON { get; set; }
    public string MACUAHANG { get; set; }
    public string MANHANVIEN { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
    public virtual CUAHANG CUAHANG { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<THONGKEHOADON> THONGKEHOADONs { get; set; }
    public virtual NHANVIEN NHANVIEN { get; set; }
}
